<?php

return [
    'page_title' => 'REPORTS',
    'page_subtitle' => 'Overall Performance Summary',
    'all_services' => 'All Services',
    'export' => 'Export',
    'export_started' => 'Downloading report…',

    'total_revenue' => 'Total Revenue',
    'total_quotations' => 'Total Quotations',
    'conversion_rate' => 'Conversion Rate',
    'avg_deal_value' => 'Avg Deal Value',
    'conversion_hint' => 'Converted projects ÷ quotations issued',

    'overall_trend' => 'Overall Trend',
    'breakdown_by_service' => 'Breakdown by Service',
    'col_service' => 'Service',
    'col_sales' => 'Sales',
    'col_target' => 'Target',
    'col_projects' => 'Projects',
    'col_achievement' => 'Achievement',
    'col_status' => 'Status',

    'csv' => [
        'filename' => 'dbena-report',
        'service' => 'Service',
        'sales' => 'Total Sales (RM)',
        'target' => 'Target (RM)',
        'projects' => 'Project Count',
        'achievement' => 'Achievement (%)',
        'status' => 'Status',
        'period' => 'Period',
        'generated' => 'Generated at',
        'generated_by' => 'Generated by',
    ],
];
