<?php

return [
    'page_title' => 'OWNER PERFORMANCE REPORT',
    'page_subtitle' => 'PIC assessment with commentary & actions',

    'period' => [
        'weekly' => 'Weekly',
        'monthly' => 'Monthly',
        'yearly' => 'Yearly',
    ],
    'label' => [
        'weekly' => 'Week :week, :month :year',
    ],

    'filter_period' => 'Period',
    'filter_week' => 'Week',
    'filter_service' => 'Service',
    'all_services' => 'All Services',
    'filter_owner' => 'Owner',
    'all_owners' => 'All Owners',
    'export_pdf_owner' => 'Export PDF — :owner',
    'export_hint_owner' => 'Report for a single owner only',
    'report_for_owner' => 'Personal Report — :owner',
    'export_pdf' => 'Export PDF',
    'generated_at' => 'Generated at',
    'generated_by' => 'Generated by',

    'summary' => [
        'title' => 'Team Summary',
        'headline' => 'Team score :score% for the :period period — :owners PICs tracking :metrics metrics.',
        'team_score' => 'Team Score',
        'owners' => 'PIC Count',
        'metrics_tracked' => 'Metrics Tracked',
        'on_track' => 'On Target',
        'critical' => 'Critical',
        'pending' => 'Not Updated',
        'top_performer' => 'Top Performer',
        'needs_attention' => 'Needs Attention',
        'none_need_attention' => 'All PICs are in good standing.',
    ],

    'owner' => [
        'score' => 'Score',
        'grade' => 'Grade',
        'metrics' => 'metrics',
        'on_track' => 'On Target',
        'has_plan' => 'Has Plan',
        'no_plan' => 'No Plan',
        'pending' => 'Not Updated',
        'avg_achievement' => 'Avg Achievement',
        'vs_previous' => 'vs last period',
    ],

    'commentary_title' => 'Performance Commentary',
    'actions_title' => 'Required Actions',
    'metrics_title' => 'Metric Breakdown',

    'col' => [
        'metric' => 'Metric',
        'service' => 'Service',
        'actual' => 'Actual',
        'target' => 'Target',
        'achievement' => 'Achievement',
        'status' => 'Status',
        'plan' => 'Action Plan',
    ],

    'priority' => [
        'high' => 'High',
        'medium' => 'Medium',
        'low' => 'Low',
    ],

    'verdict' => [
        'excellent' => 'excellent performance',
        'good' => 'good performance',
        'fair' => 'fair performance',
        'weak' => 'weak performance',
        'critical' => 'critical performance',
    ],

    'commentary' => [
        'overall' => ':name scored :score% (Grade :grade) — :verdict, with :green of :total metrics meeting target.',
        'trend_up' => 'Performance improved :delta points against the previous period (:previous%), showing positive momentum worth sustaining.',
        'trend_down' => 'Performance dropped :delta points against the previous period (:previous%) — this decline needs addressing before it becomes a pattern.',
        'trend_flat' => 'Performance held steady against the previous period (:previous%), with no material change.',
        'trend_none' => 'No prior period data available for trend comparison.',
        'worst' => 'Furthest behind: :list. These need immediate focus.',
        'best' => 'Metrics exceeding target: :list. The practices here are worth replicating elsewhere.',
        'no_plan' => ':count metrics missed target with NO action plan recorded (:list). This is a discipline gap, not merely a performance gap.',
        'has_plan' => ':count metrics are behind target but already have action plans — progress needs weekly monitoring.',
        'pending' => ':count of :total metrics remain un-updated for this period, leaving the assessment incomplete.',
        'financial_gap' => 'Total financial gap to close: :amount.',
    ],

    'action' => [
        'write_plan' => 'Write an action plan for ":metric"',
        'write_plan_detail' => 'Actual :actual against target :target (:service). This metric is Red because no plan is on record.',
        'update_data' => 'Update outstanding weekly data',
        'update_data_detail' => ':count metrics have no input at all for this period. The assessment cannot be treated as final until the data is complete.',
        'revise_plan' => 'Revise the action plan for ":metric"',
        'revise_plan_detail' => 'The existing plan is not landing — achievement is still :pct%. Consider a different approach.',
        'escalate' => 'Escalate to management for support',
        'escalate_detail' => 'A score below 40% points to a structural problem rather than individual performance alone. A joint review with management is recommended.',
        'weekly_review' => 'Hold a focused weekly review',
        'weekly_review_detail' => 'A mid-range score suggests recovery is within reach. Weekly review of the weakest metrics can lift the score quickly.',
        'maintain' => 'Maintain current momentum',
        'maintain_detail' => 'Performance is in good shape. Focus on consistency and document what is working.',
    ],

    'no_data' => 'No PIC performance data for this period.',
    'no_data_hint' => 'Make sure Weekly Critical Data has been filled in and a PIC is assigned to each metric.',
];
